language: julia
codecov: true
coveralls: true
os:
  - linux
  - osx
julia:
  - 1
  - nightly
notifications:
  email: false
after_success:
  - julia -e 'using Pkg; Pkg.add("Coverage"); using Coverage; Codecov.submit(process_folder()); Coveralls.submit(process_folder())'
